language: ruby
env:
  - "ACTIVESUPPORT_VERSION=3.1"
  - "ACTIVESUPPORT_VERSION=3.2"
  - "ACTIVESUPPORT_VERSION=4"
rvm:
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - jruby-18mode
  - jruby-19mode
  - rbx-19mode
  - ruby-head
  - jruby-head
  - 1.8.7
  - ree
services:
  - mongodb
